#! /bin/sh
abs_top_builddir=/home/vagrant/code/smalltalk-3.2
: ${LIBTOOL=$abs_top_builddir/libtool}

exec $LIBTOOL --mode=execute  -dlopen "${abs_top_builddir}/packages/dbd-sqlite/dbd-sqlite3.la" -dlopen "${abs_top_builddir}/packages/i18n/i18n.la" -dlopen "${abs_top_builddir}/packages/iconv/iconv.la" -dlopen "${abs_top_builddir}/packages/digest/digest.la" -dlopen "${abs_top_builddir}/packages/xml/expat/expat.la" -dlopen "${abs_top_builddir}/packages/zlib/zlib.la" $abs_top_builddir/gst ${1+"$@"}
